import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#505252",
        "surface-dim": "#0e0e0e",
        "tertiary-container": "#fc0078",
        "secondary-container": "#454747",
        "surface-tint": "#f3ffca",
        "secondary-fixed-dim": "#d4d4d4",
        "on-error": "#450900",
        "on-tertiary": "#47001d",
        "on-tertiary-fixed-variant": "#760035",
        "primary-container": "#cafd00",
        "tertiary-fixed": "#ff8eac",
        "on-primary-fixed": "#3a4a00",
        "tertiary-dim": "#e4006c",
        "surface": "#0e0e0e",
        "on-error-container": "#ffd2c8",
        "surface-container": "#1a1919",
        "inverse-on-surface": "#565554",
        "on-primary-container": "#4a5e00",
        "on-background": "#ffffff",
        "inverse-surface": "#fcf8f8",
        "surface-container-highest": "#262626",
        "tertiary": "#ff6b98",
        "outline-variant": "#494847",
        "inverse-primary": "#516700",
        "on-tertiary-fixed": "#380015",
        "on-primary-fixed-variant": "#526900",
        "primary-dim": "#beee00",
        "surface-container-low": "#131313",
        "on-primary": "#516700",
        "error-dim": "#d53d18",
        "error-container": "#b92902",
        "primary-fixed": "#cafd00",
        "secondary": "#e2e2e2",
        "secondary-dim": "#d4d4d4",
        "surface-bright": "#2c2c2c",
        "on-secondary-container": "#d0d0d0",
        "primary-fixed-dim": "#beee00",
        "surface-container-high": "#201f1f",
        "secondary-fixed": "#e2e2e2",
        "tertiary-fixed-dim": "#ff769e",
        "on-secondary-fixed-variant": "#5a5c5c",
        "primary": "#f3ffca",
        "on-tertiary-container": "#000000",
        "on-secondary-fixed": "#3e4040",
        "background": "#0e0e0e",
        "surface-container-lowest": "#000000",
        "on-surface": "#ffffff",
        "outline": "#777575",
        "error": "#ff7351",
        "on-surface-variant": "#adaaaa",
        "surface-variant": "#262626"
      },
      fontFamily: {
        headline: ["var(--font-space-grotesk)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-space-grotesk)", "sans-serif"]
      },
      borderRadius: { DEFAULT: "0px", lg: "0px", xl: "0px", full: "9999px" },
    },
  },
  plugins: [],
} satisfies Config;
